In [1]:
import torch

In [2]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [3]:
a[0]

tensor(1.)

In [5]:
a[7]

IndexError: index 7 is out of bounds for dimension 0 with size 5

In [ ]:
a[1:3]

In [ ]:
print(float(a[1]))

In [ ]:
a[0] = 5.0
print(a)

In [6]:
b = torch.zeros(5)
print(b)

tensor([0., 0., 0., 0., 0.])


In [7]:
b[1] = 10.0
print(b)

tensor([ 0., 10.,  0.,  0.,  0.])


In [8]:
x = torch.empty(5, 3)
print(x)

tensor([[-1.6133e-37,  3.0634e-41, -1.6072e-37],
        [ 3.0634e-41,  8.9683e-44,  0.0000e+00],
        [ 1.1210e-43,  0.0000e+00, -1.6174e-37],
        [ 3.0634e-41,  2.2421e-44,  0.0000e+00],
        [        nan,  1.0013e+33,  4.4721e+21]])


In [9]:
y = torch.rand(5, 3)
print(y)

tensor([[0.8112, 0.0984, 0.4772],
        [0.5246, 0.5603, 0.1440],
        [0.4832, 0.3107, 0.8831],
        [0.4807, 0.9348, 0.0385],
        [0.6167, 0.4095, 0.1327]])


In [10]:
x = torch.ones(5, 5, dtype=torch.long)
print(x)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])


In [11]:
x = torch.ones(5, 5, dtype=torch.int32)
print(x)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)


In [12]:
x = torch.tensor([5.5, 15.5])
print(x)

tensor([ 5.5000, 15.5000])


In [13]:
y = x.new_ones(5, 3, dtype=torch.double)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [14]:
a = torch.tensor([1.0, 2.0, 3.0, 4.0])
print(a)

tensor([1., 2., 3., 4.])


In [16]:
print(a.size())

torch.Size([4])


In [17]:
a = torch.tensor([[5.0, 6.0], [8.0, 9.0], [10.0, 11.0]])
print(a)

tensor([[ 5.,  6.],
        [ 8.,  9.],
        [10., 11.]])


In [19]:
print(a.shape)

torch.Size([3, 2])


In [20]:
print(a.size())

torch.Size([3, 2])
