In [1]:
import torch

In [2]:
a = torch.ones(10, 2, dtype=torch.double)
print(a)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)


In [3]:
type(a)

torch.Tensor

In [5]:
a.dtype

torch.float64

In [6]:
b = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)
print(b)

tensor([[1, 2],
        [3, 4]], dtype=torch.int16)


In [7]:
x = torch.zeros(10, 3).double()
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


In [8]:
x = torch.zeros(10, 3).short()
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int16)


In [9]:
x = torch.zeros(10, 3).to(torch.double)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


In [12]:
a = torch.tensor([[1.1, 2.2, 3.3], [4.4, 5.5, 6.6], [7.7, 8.8, 9.9]]).to(torch.int32)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)


In [14]:
a = torch.ones(3,2)
aT = torch.transpose(a, 0, 1)
print(a.shape, aT.shape)

torch.Size([3, 2]) torch.Size([2, 3])


In [15]:
x = torch.tensor([[4, 5], [3, 1], [7, 9]], dtype=torch.double)
print(x.storage())

 4.0
 5.0
 3.0
 1.0
 7.0
 9.0
[torch.DoubleStorage of size 6]


In [17]:
b = x.storage()
print(b[4])

7.0


In [18]:
x = torch.tensor([[4, 5], [3, 1], [7, 9]], dtype=torch.double)
print(x[0])

tensor([4., 5.], dtype=torch.float64)


In [19]:
print(x[0, 1])

tensor(5., dtype=torch.float64)


In [20]:
x[0][1]

tensor(5., dtype=torch.float64)

In [21]:
x[2][1] = 100
print(x)

tensor([[  4.,   5.],
        [  3.,   1.],
        [  7., 100.]], dtype=torch.float64)


In [22]:
x = torch.rand(5, 6, requires_grad=True)
y = torch.rand(5, 6)

In [23]:
print(x)

tensor([[0.0674, 0.4845, 0.4335, 0.8675, 0.9592, 0.0520],
        [0.1796, 0.3358, 0.2391, 0.6457, 0.9742, 0.7476],
        [0.3223, 0.1997, 0.6183, 0.9513, 0.9449, 0.1582],
        [0.7673, 0.5864, 0.8205, 0.6337, 0.0313, 0.7788],
        [0.4908, 0.7499, 0.8256, 0.2785, 0.4575, 0.1550]], requires_grad=True)


In [24]:
print(y)

tensor([[0.9394, 0.3125, 0.7123, 0.7214, 0.5499, 0.7952],
        [0.6576, 0.1813, 0.7476, 0.4038, 0.8660, 0.0061],
        [0.6212, 0.3085, 0.8321, 0.2402, 0.8689, 0.2773],
        [0.8036, 0.5433, 0.0661, 0.8628, 0.7612, 0.2962],
        [0.8861, 0.6341, 0.9919, 0.3824, 0.8621, 0.1763]])


In [25]:
b = torch.zeros(3, 3)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [26]:
b.fill_diagonal_(100)

tensor([[100.,   0.,   0.],
        [  0., 100.,   0.],
        [  0.,   0., 100.]])

In [27]:
x = torch.tensor([1, 2, 3])
print(x)

tensor([1, 2, 3])


In [28]:
x.repeat(4, 2)

tensor([[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]])

In [29]:
x.repeat(4, 4)

tensor([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]])