In [1]:
import torch

In [3]:
x = torch.tensor([i for i in range(1, 6)], dtype=torch.float)
print(x)

tensor([1., 2., 3., 4., 5.])


In [4]:
torch.mean(x)

tensor(3.)

In [5]:
torch.median(x)

tensor(3.)

In [6]:
torch.std(x)

tensor(1.5811)

In [7]:
torch.var(x)

tensor(2.5000)

In [8]:
a = torch.tensor([1,2,3,4,5], dtype=torch.float)
b = torch.tensor([6,7,8,9,10], dtype=torch.float)

In [9]:
print(a + b)

tensor([ 7.,  9., 11., 13., 15.])


In [10]:
print(a - b)

tensor([-5., -5., -5., -5., -5.])


In [11]:
print(a * b)

tensor([ 6., 14., 24., 36., 50.])


In [12]:
print(a @ b)

tensor(130.)


In [13]:
a.add_(b)

tensor([ 7.,  9., 11., 13., 15.])

In [15]:
a

tensor([ 7.,  9., 11., 13., 15.])

In [16]:
a.sub_(b)

tensor([1., 2., 3., 4., 5.])

In [17]:
a.mul_(b)

tensor([ 6., 14., 24., 36., 50.])

In [19]:
torch.numel(a)

5

In [18]:
i = torch.eye(5)
print(i)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [22]:
u = torch.Tensor(2, 3).uniform_(0, 1)
print(u)

tensor([[0.5204, 0.8706, 0.9094],
        [0.0336, 0.3043, 0.1645]])


In [21]:
b = torch.Tensor(3, 2).bernoulli_()
print(b)

tensor([[1., 0.],
        [1., 1.],
        [0., 1.]])


In [23]:
n = torch.Tensor(2, 4).normal_()
print(n)

tensor([[-0.0980, -0.9156, -0.1081, -0.6430],
        [-0.7828,  2.4788, -0.4817, -0.1146]])


In [39]:
z = torch.Tensor(5, 5).multinomial(10, replacement=True)
print(z)

tensor([[1, 2, 2, 0, 0, 1, 3, 3, 0, 0],
        [3, 0, 4, 4, 3, 0, 4, 4, 3, 1],
        [3, 0, 2, 4, 1, 0, 1, 4, 0, 2],
        [3, 4, 1, 1, 0, 0, 0, 3, 0, 1],
        [0, 3, 3, 2, 0, 3, 0, 0, 2, 0]])
