In [1]:
import torch

In [2]:
a = torch.zeros(2, 3)
print(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [3]:
type(a)

torch.Tensor

In [4]:
a.size()

torch.Size([2, 3])

In [5]:
a.dim()

2

In [6]:
n = torch.zeros(2, 3, names=('Rows', 'Cols'))
print(n)

tensor([[0., 0., 0.],
        [0., 0., 0.]], names=('Rows', 'Cols'))


<ipython-input-6-8d4b097616cd>:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:848.)
  n = torch.zeros(2, 3, names=('Rows', 'Cols'))


In [7]:
n.names

('Rows', 'Cols')

In [8]:
n.names[0]

'Rows'

In [9]:
renamed = n.rename(Rows='A', Cols='B')
print(renamed)

tensor([[0., 0., 0.],
        [0., 0., 0.]], names=('A', 'B'))


In [10]:
x = torch.randn(1, 2, 3, 4, 5, names=(None, 'A', 'B', 'C', 'D'))
print(x)

tensor([[[[[ 0.1295, -0.4231, -0.1683, -1.4635,  0.8102],
           [-0.7402, -0.1405,  0.9718, -0.6447,  0.6092],
           [ 1.3711,  0.1991,  2.6805, -0.4328,  0.1540],
           [-1.9103,  0.3980, -0.1643,  0.1843, -1.1431]],

          [[-0.5340,  0.5589,  1.4689, -0.5456,  0.5031],
           [ 0.2052, -1.3956, -0.0193,  2.4694,  0.4656],
           [-0.3699, -1.0906,  0.8005, -0.2038, -1.7706],
           [-0.5398, -0.7503,  0.3851, -0.8270, -1.9117]],

          [[ 0.2639, -1.7436,  0.2706, -0.5953, -2.0519],
           [-0.3586, -1.2000, -0.7615,  1.3344,  0.9340],
           [-0.2681, -2.1388,  1.0880, -0.3716,  1.5437],
           [ 1.5647,  0.3385,  0.6267,  0.4872,  0.6373]]],


         [[[-1.4155,  1.1819, -0.2906, -1.0508, -0.8251],
           [-0.7999, -0.6270, -0.4148, -0.2968, -0.2886],
           [ 0.4178, -0.7817,  0.2318,  0.9572, -0.8588],
           [-1.8904, -0.8284, -0.2952, -0.2851,  1.3527]],

          [[ 1.3341, -0.1407, -0.9801,  0.1382,  1.1024],
    

In [15]:
a = torch.randn(4, names=('X',))
b = torch.randn(4)
c = torch.randn(4, names=('Y',))

In [17]:
print(a)
print(b)
print(c)

tensor([0.6420, 1.2617, 0.2309, 0.7357], names=('X',))
tensor([ 1.9184, -1.6670, -0.6218, -0.5244])
tensor([-2.2145,  0.7248, -0.8774,  0.1062], names=('Y',))


In [18]:
print(a + b)

tensor([ 2.5604, -0.4053, -0.3910,  0.2113], names=('X',))


In [19]:
print(a + c)

RuntimeError: Error when attempting to broadcast dims ['X'] and dims ['Y']: dim 'X' and dim 'Y' are at the same position from the right but do not match.

In [20]:
print(b + c)

tensor([-0.2961, -0.9421, -1.4992, -0.4182], names=('Y',))
