In [1]:
import torch

In [2]:
float_tensor = torch.ones(5, dtype=torch.float)
print(float_tensor)

tensor([1., 1., 1., 1., 1.])


In [3]:
float_tensor.dtype

torch.float32

In [5]:
float_tensor.device

device(type='cpu')

In [6]:
float_tensor.layout

torch.strided

In [7]:
float_tensor.size()

torch.Size([5])

In [8]:
float_tensor.dim()

1

***

In [9]:
double_tensor = torch.ones(1, dtype=torch.double)
print(double_tensor)

tensor([1.], dtype=torch.float64)


In [11]:
double_tensor.dtype

torch.float64

In [12]:
double_tensor.device

device(type='cpu')

***

In [14]:
complex_float = torch.ones(1, dtype=torch.complex64)
print(complex_float)

tensor([1.+0.j])


In [15]:
complex_float.dtype

torch.complex64

In [16]:
complex_double = torch.ones(1, dtype=torch.complex128)
print(complex_double)

tensor([1.+0.j], dtype=torch.complex128)


In [17]:
complex_double.dtype

torch.complex128

***

In [18]:
int_tensor = torch.ones(1, dtype=torch.int)
print(int_tensor)

tensor([1], dtype=torch.int32)


In [19]:
long_tensor = torch.ones(5, dtype=torch.long)
print(long_tensor)

tensor([1, 1, 1, 1, 1])


In [20]:
long_tensor.dtype

torch.int64

***

In [23]:
uint_tensor = torch.ones(2, dtype=torch.uint8)
print(uint_tensor)

tensor([1, 1], dtype=torch.uint8)


***

In [26]:
bool_tensor = torch.zeros(5, dtype=torch.bool)
print(bool_tensor)

tensor([False, False, False, False, False])


In [27]:
bool_tensor.dtype

torch.bool

***

In [28]:
long_zerodim = torch.tensor(5, dtype=torch.long)
print(long_zerodim)

tensor(5)


In [29]:
long_zerodim.dim()

0