In [1]:
import torch

In [2]:
double_type = torch.ones(5, 2, dtype=torch.double)
print(double_type)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)


In [3]:
short_type = torch.tensor([[1,2], [3,4], [5,6]], dtype=torch.short)
print(short_type)

tensor([[1, 2],
        [3, 4],
        [5, 6]], dtype=torch.int16)


In [4]:
double_t = torch.zeros(5, 2).to(torch.double)
print(double_t)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)


In [8]:
double_t = torch.zeros(5, 2).double()
print(double_t)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)


In [7]:
short_t = torch.zeros(5, 2).short()
print(short_t)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]], dtype=torch.int16)
