In [1]:
import torch

In [2]:
a = torch.ones(3, 2)
b = torch.ones(3, 2)
print(a + b)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


In [3]:
print(a)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [4]:
a.add_(b)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])

In [5]:
print(a)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


In [6]:
print(b)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [8]:
b.mul_(a)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])

In [9]:
print(b)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


In [10]:
a.div_(b)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [11]:
print(a)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [12]:
a.exp_()

tensor([[2.7183, 2.7183],
        [2.7183, 2.7183],
        [2.7183, 2.7183]])

In [13]:
a.cos_()

tensor([[-0.9117, -0.9117],
        [-0.9117, -0.9117],
        [-0.9117, -0.9117]])

In [14]:
a.bernoulli_()

tensor([[1., 1.],
        [0., 0.],
        [0., 0.]])

In [15]:
a.uniform_()

tensor([[0.6119, 0.1264],
        [0.6503, 0.8932],
        [0.9447, 0.0072]])

In [16]:
x = torch.ones(3, 3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [17]:
x.zero_()

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])