In [1]:
import torch

In [2]:
x = torch.tensor([[1.0, 2.0], [3., 4.], [5., 6.]])

In [3]:
x.size()

torch.Size([3, 2])

In [4]:
x.dim()

2

In [5]:
xT = x.t()

In [6]:
print(xT)

tensor([[1., 3., 5.],
        [2., 4., 6.]])


In [7]:
xT.size()

torch.Size([2, 3])

In [8]:
xT.dim()

2

In [9]:
id(x.storage()) == id(xT.storage())

True

In [10]:
a = torch.ones(3,4,5)
print(a)

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])


In [11]:
aT = a.transpose(0, 1)
print(aT)

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])


In [12]:
print(a.size())

torch.Size([3, 4, 5])


In [13]:
print(aT.size())

torch.Size([4, 3, 5])
