In [2]:
import csv
import torch
import numpy as np

In [3]:
# !wget https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv
# !wget https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv

In [4]:
kwargs = dict(delimiter=';', dtype=np.float32, skiprows=1)
red_np = np.loadtxt('winequality-red.csv', **kwargs)
white_np = np.loadtxt('winequality-white.csv', **kwargs)

In [12]:
wine_numpy = np.vstack((red_np, white_np))

In [13]:
wine_tensor = torch.from_numpy(wine_numpy)

In [14]:
data = wine_tensor[:, :-1]

In [21]:
target = wine_tensor[:, -1].to(torch.long)

In [17]:
target.unique()

tensor([3., 4., 5., 6., 7., 8., 9.])

In [18]:
target_1hot = torch.zeros(target.shape[0], 10)

In [19]:
target_1hot

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [22]:
result = target_1hot.scatter_(1, target.unsqueeze(1), 1.0)

In [23]:
print(result)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
