In [1]:
import torch

In [2]:
x = torch.ones(2, 2, requires_grad=True)

In [3]:
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [4]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [6]:
print(y.grad_fn)

In [7]:
z = y * y * 3
print(z)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)


In [8]:
out = z.mean()
print(out)

tensor(27., grad_fn=<MeanBackward0>)


In [9]:
out.backward()

In [10]:
print(x.grad) # d (out)/ d (x)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


***

In [11]:
a = torch.randn(2, 2)
print(a)

tensor([[ 1.0055, -0.5495],
        [-0.6921, -0.2422]])


In [12]:
a = (a*3)/(a-1)
print(a)

tensor([[551.6336,   1.0639],
        [  1.2271,   0.5850]])


In [13]:
print(a.requires_grad)

False


In [14]:
a.requires_grad_(True)

tensor([[551.6336,   1.0639],
        [  1.2271,   0.5850]], requires_grad=True)

In [15]:
b = (a*a).sum()
print(b)

tensor(304302.5938, grad_fn=<SumBackward0>)


***

In [17]:
x = torch.randn(3, requires_grad=True)

y = x * 2

while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([  573.4421,  -241.7017, -1003.4727], grad_fn=<MulBackward0>)


In [18]:
v = torch.tensor([0.1, 1.0, 0.00001], dtype=torch.float)

In [19]:
y.backward(v)
print(x.grad)

tensor([2.0480e+02, 2.0480e+03, 2.0480e-02])


In [20]:
print(x.requires_grad)

True


In [22]:
with torch.no_grad():
    print((x*2).requires_grad)


False


In [23]:
print(x.requires_grad)

True


In [24]:
y = x.detach()
print(y.requires_grad)

False
